version: 2
jobs:
  build:
    machine: true
    environment:
      TZ: "/usr/share/zoneinfo/Europe/paris"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo add-apt-repository ppa:ondrej/php
            sudo apt-get update && sudo apt-get install -y npm sshpass php7.0 php7.0-xml
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
            sudo mv composer.phar /usr/local/bin/composer
            sudo chmod a+x /usr/local/bin/composer
      - run:
          name: Install Docker Compose
          command: |
            sudo pip uninstall -y docker-compose
            sudo rm /usr/local/bin/docker-compose
            sudo curl -o /usr/local/bin/docker-compose -L "https://github.com/docker/compose/releases/download/1.15.0/docker-compose-$(uname -s)-$(uname -m)"
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Install CasperJS & JUnit
          command: |
            sudo npm install -g casperjs@1.1.3
            sudo npm install -g junit-viewer
      - run:
          name: Configure Environment File
          command: |
            sed -i -e "s/{HIPAY_API_USER_TEST\}/$HIPAY_API_USER_TEST/" ./bin/conf/stage/hipay.env.sample
            sed -i -e "s/{HIPAY_API_PASSWORD_TEST\}/$HIPAY_API_PASSWORD_TEST/" ./bin/conf/stage/hipay.env.sample
            sed -i -e "s/{HIPAY_TOKENJS_PUBLICKEY_TEST\}/$HIPAY_TOKENJS_PUBLICKEY_TEST/" ./bin/conf/stage/hipay.env.sample
            sed -i -e "s/{HIPAY_TOKENJS_USERNAME_TEST\}/$HIPAY_TOKENJS_USERNAME_TEST/" ./bin/conf/stage/hipay.env.sample
            sed -i -e "s/{HIPAY_SECRET_PASSPHRASE_TEST\}/$HIPAY_SECRET_PASSPHRASE_TEST/" ./bin/conf/stage/hipay.env.sample
            sed -i -e "s/{LOGIN_BACKEND\}/$LOGIN_BACKEND/" ./bin/conf/stage/test.env.sample
            sed -i -e "s/{PASS_BACKEND\}/$PASS_BACKEND/" ./bin/conf/stage/test.env.sample
            sed -i -e "s/{LOGIN_PAYPAL\}/$LOGIN_PAYPAL/" ./bin/conf/stage/test.env.sample
            sed -i -e "s/{PASS_PAYPAL\}/$PASS_PAYPAL/" ./bin/conf/stage/test.env.sample
      - run:
          name: Add vhost
          command: echo 127.0.0.1 local-magento.hipay.com | sudo tee -a /etc/hosts
      - run:
          name: Generate DockerFiles
          command: |
            sh bin/docker/generate_dockerfile.sh
            docker --version
            docker-compose --version
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/php5-6.tar
            - /caches/mysql-smtp.tar
            - /caches/php7-0.tar
      - run:
          name: Load Docker image PHP 5.6 layer cache
          command: |
            set +o pipefail
            docker load -i /caches/php5-6.tar | true
      - run:    
          name: Build application Docker image PHP 5.6
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.stage.yml build
      - run:
          name: Save Docker image PHP 5.6 layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/php5-6.tar magento1_web_php5_6 php:5.6-apache
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/php5-6.tar
      - run:
          name: Load Docker Compose images
          command: |
            set +o pipefail
            docker load -i /caches/mysql-smtp.tar | true
      - run:
          name: Up PHP 5.6 container
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.stage.yml up -d
            echo "Wait 60sec to have ready container" && sleep 60
            curl --retry 30 --retry-delay 3 -v $MAGENTO_URL:$PORT_WEB
            curl --retry 30 --retry-delay 3 -v $URL_MAILCATCHER
      - run:
          name: Save Docker Compose images
          command: |
            mkdir -p /caches
            docker save -o /caches/mysql-smtp.tar mysql:5.6.23 schickling/mailcatcher
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/mysql-smtp.tar
      - run:
          name: Launch Tests PHP 5.6
          command: |
            sh bin/tests/casper_run_circle.sh
            junit-viewer --results=bin/tests/result.xml \
              --save=bin/tests/report-php5-6.html --minify=false --contracted
            if [ -d bin/tests/errors/ ]; then
              rm -rf bin/tests/errors/
            fi
      - store_artifacts:
          path: bin/tests/errors/
          prefix: screenshots_php_5_6
      - run:
          name: Stop PHP 5.6 container
          command: |
            docker-compose stop
            docker-compose rm -fv
      - run:
          name: Load Docker image PHP 7.0 layer cache
          command: |
            set +o pipefail
            docker load -i /caches/php7-0.tar | true
      - run:    
          name: Build application Docker image PHP 7.0
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.stage-php7-0.yml build
      - run:
          name: Save Docker image PHP 7.0 layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/php7-0.tar magento1_web_php7_0 php:7.0-apache
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/php7-0.tar
      - run:
          name: Up PHP 7.0 container
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.stage-php7-0.yml up -d
            sleep 60
            curl --retry 30 --retry-delay 3 -v $MAGENTO_URL:$PORT_WEB
      - run:
          name: Launch Tests PHP 7.0
          command: |
            sh bin/tests/casper_run_circle.sh
            junit-viewer --results=bin/tests/result.xml \
              --save=bin/tests/report-php7-0.html --minify=false --contracted
      - store_artifacts:
          path: bin/tests/errors/
          prefix: screenshots_php_7_0
      - store_artifacts:
          path: bin/tests/report*.html
          prefix: reports
      - run:
          name: Package Extension
          command: |
            mv composer.json.dist composer.json
            sh ./bin/deployment/packaging.sh
      - store_artifacts:
          path: /dist/*.tgz
          prefix: package
      - deploy:
          name: Push module Magento1 to Docker-Machine
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              sh ./bin/deployment/deploy_project.sh
            fi