version: "2.1"

networks:
  magento:
    internal: true
  outside:
    external: true

services:
  magento:
    networks:
      - magento
      - outside
    container_name: hipay-mg1-$CI_JOB_ID
    build:
      context: .
      dockerfile: ./bin/docker/php5-6/Dockerfile
    environment:
      - SAMPLE_DATA_VERSION=1.9
      - MAGENTO_VERSION=1.9.3.8
    env_file:
      - ./bin/conf/stage/hipay.env.sample
      - ./bin/conf/stage/mage.env.sample
      - ./bin/conf/stage/mysql.env.sample
    volumes:
      - ./log:/var/www/htdocs/var/log
    depends_on:
      - mysql
  mysql:
    container_name: hipay-mysql-mg1-$CI_JOB_ID
    env_file:
       - ./bin/conf/stage/mysql.env.sample
    networks:
      - magento
  smtp:
    container_name: hipay-smtp-mg1-$CI_JOB_ID
    networks:
      - magento
