version: '3.2'
services:
  web:
    build: 
      context: ./bin/docker/php5-6/
      dockerfile: ./bin/docker/php5-6/Dockerfile
    links:
      - mysql
      - smtp
  mysql:
    image: mysql:5.6.23
  smtp:
    image: schickling/mailcatcher
    container_name: smtp-hipay-mg-latest
    ports:
      - "1095:1080"
