version: '3.2'
services:
  web:
    container_name: jira-mg-latest.hipay-pos-platform.com
    build: 
      context: .
      dockerfile: ./bin/docker/php5-6/Dockerfile
      cache_from:
        - php5-6:php5-6
    ports:
        - "80:80"
    env_file:
      - ./bin/conf/stage/hipay.env.sample
      - ./bin/conf/stage/mage.env.sample
      - ./bin/conf/stage/mysql.env.sample
  mysql:
    image: mysql:5.6.23
    env_file:
       - ./bin/conf/stage/mysql.env.sample
